### ISSUE TITLE
[기획] Spring @Transactional에 대해서

### ISSUE THREAD

**Issue by ppusda** [Bisi3asi/Planters#25]
## Spring `@Transactional`에 대해서

> 학습 목표 : Spring 의 `@Transactional`에 대해 깊게 이해한다.

## 글 내용
1. Transaction 이란?
    * ACID 원칙
2. `@Transactional`
    * 사용법
    * 구조
    * 속성 
      * value (+ 트랜잭션 매니저, JTA)
      * propagation (전파레벨)
      * isolation (동시성 문제와 격리수준)
      * readOnly (읽기 전용의 이점과 동작, + Flush Mode)
      * timeout (시간 제한)
      * rollbackFor, rollbackForClassName (예외 시 롤백 처리 결정, + Checked Exception, Unchecked Exception)
      * noRollbackFor, noRollbackForClassName (예외 시 롤백 처리 결정)
3. 부록 - 낙관적 락, 비관적 락
    * 락
    * 낙관적 락
    * 비관적 락 (+ 공유 락, 배타 락)
    * 격리 수준 속성과의 관계
    * 읽기 전용 속성과의 관계
4. 정리

## REFERENCE
[[MYSQL] 📚 트랜잭션(Transaction) 개념 & 사용 💯 완벽 정리](https://inpa.tistory.com/entry/MYSQL-%F0%9F%93%9A-%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98Transaction-%EC%9D%B4%EB%9E%80-%F0%9F%92%AF-%EC%A0%95%EB%A6%AC)

[[Spring DB] 4. 스프링의 트랜잭션 매니저](https://everenew.tistory.com/266)

[Spring & JTA(분산 트랜잭션)](https://devssul.tistory.com/33)

[[Spring] 트랜잭션의 전파 설정별 동작](https://deveric.tistory.com/86)

[[Spring] @Transactional 어노테이션 이해하기(1) 전파유형(Propagation) 과 격리수준(Isolation)](https://colevelup.tistory.com/34)

[[Spring] Spring 트랜잭션의 세부 설정(전파 속성, 격리수준, 읽기전용, 롤백/커밋 예외 등) - (2/3)](https://mangkyu.tistory.com/169)

[Non-Repeatable Read vs Phantom Read?](https://stackoverflow.com/questions/11043712/non-repeatable-read-vs-phantom-read)

[@Transactional(readOnly = true)를 왜 붙여야 하나요](https://hungseong.tistory.com/74)

[JPA, Hibernate, 그리고 Spring Data JPA의 차이점](https://suhwan.dev/2019/02/24/jpa-vs-hibernate-vs-spring-data-jpa/)

[JPA & Hibernate Flush Mode](https://keencho.github.io/posts/jpa-flush/)

[[Java] Checked Exception vs Unchecked Exception 정리](https://devlog-wjdrbs96.tistory.com/351)

[[JPA] @Transactional(readOnly = true)의 효과와 사용 시 주의할 점](https://seungjjun.tistory.com/256)

[[JPA] 낙관적 락(Optimistic Lock)과 비관적 락(Pessimistic Lock)에 대해](https://mozzi-devlog.tistory.com/37)

[JPA의 낙관적 락과 비관적 락을 통해 엔티티에 대한 동시성 제어하기](https://hudi.blog/jpa-concurrency-control-optimistic-lock-and-pessimistic-lock/)

[낙관적 락과 비관적 락은 갱신 손실 문제를 어떻게 해결하는가](https://velog.io/@balparang/%EB%82%99%EA%B4%80%EC%A0%81-%EB%9D%BD%EA%B3%BC-%EB%B9%84%EA%B4%80%EC%A0%81-%EB%9D%BD%EC%9D%80-Race-Condition%EC%9D%84-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EA%B2%B0%ED%95%98%EB%8A%94%EA%B0%80)

**Comment by Bisi3asi** [comment]
맛있는 트랜잭션~
ACID 원칙부터 다루실건지 궁금하네요

개인적으로 제가 정리할 자신감이 없어서 매우 기대하고 있겠습니다
Transaction의 전파레벨, 낙관적 락 흐흐

@ppusda
