### ISSUE TITLE
[작성] 이펙티브 자바 - 2장 객체 생성과 파괴 (전반부, item1~5)

### ISSUE THREAD

**Issue by itonse** [Bisi3asi/Planters#37]
## 이펙티브 자바 - 2장 객체 생성과 파괴 (전반부, item1~5)

> 학습 목표 : java에서 객체 생성과 파괴에 대해 이해한다

## 글 내용
1. [item1] 생성자 대신 정적 팩터리 메서드를 고려하라
   * 정적 팩터리 메서드가 public 생성자보다 선호되는 상황을 이해
2. [item2] 생성자에 매개변수가 많다면 빌더를 고려하라
   * 빌더 패턴을 사용해야 하는 시점과 그 이유
3. [item3] private 생성자나 열거 타입으로 싱글톤임을 보증하라
   * 싱글톤 패턴 이해
4. [item4] 인스턴스화를 막으려거든 private 생성자를 사용하라
   * 어떤 상황에서 인스턴스를 생성할 필요가 없는지
5. [item5] 자원을 직접 명시하지 말고 의존 객체 주입을 사용하라
   * 의존 객체 주입 개념
   * 의존 객체 주입의 장단점

## REFERENCE
1. https://product.kyobobook.co.kr/detail/S000001033066

**Comment by Bisi3asi** [comment]
평소에 Spring 프레임워크가 지키고자 하는 java OOP 규약들이 책에 모두 정리가 되어있나 본데요?
재밌을 것 같습니다!

싱글톤 패턴과 public의 지양, 인스턴스화 방지 등 이번 포스팅을 계기로 지식 학습에 많은 도움이 될 것 같네요!
기대하고 있겠습니다 😁
