### ISSUE TITLE
[작성] HTML 태그란?

### ISSUE THREAD

**Issue by chrios77** [Bisi3asi/Planters#52]
## HTML 태그란?

> 학습 목표 : HTML 태그에 대한 내용을 이해한다.

## 글 내용
1. HTML 태그(tag)
  
2. 태그의 형태
   
3. 모든 태그를 알아야 한다?

## REFERENCE
1. https://www.tcpschool.com/html-tags/intro
2. https://developer.mozilla.org/ko/docs/Web/HTML/Element
3. https://mingtrace.tistory.com/282
4. https://bono0933.tistory.com/entry/HTML-%ED%83%9C%EA%B7%B8%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80
5. https://kwiskey.tistory.com/6
6. https://info-best.tistory.com/80
7. https://velog.io/@devp1023/HTML-%ED%83%9C%EA%B7%B8%EB%9E%80
8. https://kimmychuchu.tistory.com/163

**Comment by Bisi3asi** [comment]
@chrios77 
화면 개발에 뺄래야 뺄 수 없는 HTML 태그가 등장했네요..

저도 SEO 검색 엔진 최적화 과정에서
메타 태그를 학습하면서 부수적으로 `HTML 태그에는 얼마나 더 많은 종류가 있을까?`
라고 생각했는데

제욱님 레퍼런스를 보니 심각하게 많은 것 같습니다!!

이 참에 잘 정리해주셔서 공유해주시면
핵심적인 부분을 효율적으로 학습할 수 있겠네요!

기대하고 있겠습니다 😁

**Comment by chrios77** [comment]
> @chrios77 화면 개발에 뺄래야 뺄 수 없는 HTML 태그가 등장했네요..
> 
> 저도 SEO 검색 엔진 최적화 과정에서 메타 태그를 학습하면서 부수적으로 `HTML 태그에는 얼마나 더 많은 종류가 있을까?` 라고 생각했는데
> 
> 제욱님 레퍼런스를 보니 심각하게 많은 것 같습니다!!
> 
> 이 참에 잘 정리해주셔서 공유해주시면 핵심적인 부분을 효율적으로 학습할 수 있겠네요!
> 
> 기대하고 있겠습니다 😁

앗..! 알겠습니다!! 
한 번 해보겠습니다!
