### ISSUE TITLE
[기획] 데코레이터 패턴 vs 프록시 패턴

### ISSUE THREAD

**Issue by ppusda** [Bisi3asi/Planters#9]
## 데코레이터 패턴과 프록시 패턴의 차이

> 학습 목표 : 데코레이터 패턴과 프록시 패턴을 이해하고 두 패턴의 차이점을 이해한다.

## 포스팅 내용
1. 데코레이터 패턴이란?
    * 개념, 구조
    * 특징
2. 프록시 패턴이란?
    * 개념, 구조
    * 특징
3. 두 패턴의 차이점
    * 차이점
4. 적용 시 고려사항과 활용사례
    * 적용 시 고려사항
    * 활용사례
5. 정리
 

## REFERENCE
1. [데코레이터 패턴](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EB%8D%B0%EC%BD%94%EB%A0%88%EC%9D%B4%ED%84%B0Decorator-%ED%8C%A8%ED%84%B4-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EB%B0%B0%EC%9B%8C%EB%B3%B4%EC%9E%90#%EB%8D%B0%EC%BD%94%EB%A0%88%EC%9D%B4%ED%84%B0_%ED%8C%A8%ED%84%B4_%ED%8A%B9%EC%A7%95)
2. [프록시 패턴](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%ED%94%84%EB%A1%9D%EC%8B%9CProxy-%ED%8C%A8%ED%84%B4-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EB%B0%B0%EC%9B%8C%EB%B3%B4%EC%9E%90)

**Comment by Bisi3asi** [comment]
차이점 부분에서 각 패턴 적용별 적절한 활용사례나 언제 도입되면 좋을지도 같이 작성되면 좋을 것 같습니다! @ppusda
